export const sampleData = {
  totalUsers: 1_000_000,
  activeUsers: 750_000,
  totalStreams: 5_000_000,
  revenue: 10_000_000,
  topArtist: "Taylor Swift",
  userGrowth: [
    { month: "Jan", totalUsers: 900_000, activeUsers: 700_000 },
    { month: "Feb", totalUsers: 920_000, activeUsers: 710_000 },
    { month: "Mar", totalUsers: 945_000, activeUsers: 725_000 },
    { month: "Apr", totalUsers: 960_000, activeUsers: 730_000 },
    { month: "May", totalUsers: 975_000, activeUsers: 740_000 },
    { month: "Jun", totalUsers: 990_000, activeUsers: 745_000 },
    { month: "Jul", totalUsers: 1_000_000, activeUsers: 750_000 },
    { month: "Aug", totalUsers: 1_010_000, activeUsers: 755_000 },
    { month: "Sep", totalUsers: 1_025_000, activeUsers: 760_000 },
    { month: "Oct", totalUsers: 1_035_000, activeUsers: 765_000 },
    { month: "Nov", totalUsers: 1_045_000, activeUsers: 770_000 },
    { month: "Dec", totalUsers: 1_050_000, activeUsers: 775_000 },
  ],
  revenueDistribution: [
    { source: "Subscriptions", value: 8_000_000 },
    { source: "Advertisements", value: 1_500_000 },
    { source: "Merchandise", value: 500_000 },
  ],
  topSongs: [
    { name: "Lavender Haze", streams: 1_000_000, artist: "Taylor Swift" },
    { name: "Karma", streams: 900_000, artist: "Taylor Swift" },
    { name: "As It Was", streams: 800_000, artist: "Harry Styles" },
    { name: "Bad Habit", streams: 700_000, artist: "Steve Lacy" },
    { name: "Heat Waves", streams: 600_000, artist: "Glass Animals" },
    { name: "Stay", streams: 550_000, artist: "The Kid LAROI, Justin Bieber" },
    {
      name: "Industry Baby",
      streams: 500_000,
      artist: "Lil Nas X, Jack Harlow",
    },
    {
      name: "Montero (Call Me By Your Name)",
      streams: 450_000,
      artist: "Lil Nas X",
    },
    { name: "Levitating", streams: 400_000, artist: "Dua Lipa" },
    { name: "Save Your Tears", streams: 350_000, artist: "The Weeknd" },
    { name: "Blinding Lights", streams: 300_000, artist: "The Weeknd" },
    {
      name: "Peaches",
      streams: 250_000,
      artist: "Justin Bieber, Daniel Caesar, Giveon",
    },
    { name: "Drivers License", streams: 200_000, artist: "Olivia Rodrigo" },
    { name: "Good 4 U", streams: 150_000, artist: "Olivia Rodrigo" },
    { name: "Butter", streams: 100_000, artist: "BTS" },
    { name: "Dynamite", streams: 90_000, artist: "BTS" },
    { name: "Permission to Dance", streams: 80_000, artist: "BTS" },
    { name: "Watermelon Sugar", streams: 70_000, artist: "Harry Styles" },
    { name: "Adore You", streams: 60_000, artist: "Harry Styles" },
    { name: "Falling", streams: 50_000, artist: "Harry Styles" },
  ],
  recentStreams: [
    {
      id: "1",
      songName: "Lavender Haze",
      artist: "Taylor Swift",
      dateStreamed: "2024-09-08",
      streamCount: 1_000,
      userId: "user123",
      revenueSource: "Subscriptions",
    },
    {
      id: "2",
      songName: "Karma",
      artist: "Taylor Swift",
      dateStreamed: "2024-09-07",
      streamCount: 950,
      userId: "user456",
      revenueSource: "Advertisements",
    },
    {
      id: "3",
      songName: "As It Was",
      artist: "Harry Styles",
      dateStreamed: "2024-09-06",
      streamCount: 1_200,
      userId: "user789",
      revenueSource: "Subscriptions",
    },
    {
      id: "4",
      songName: "Bad Habit",
      artist: "Steve Lacy",
      dateStreamed: "2024-09-05",
      streamCount: 880,
      userId: "user246",
      revenueSource: "Subscriptions",
    },
    {
      id: "5",
      songName: "Heat Waves",
      artist: "Glass Animals",
      dateStreamed: "2024-09-08",
      streamCount: 760,
      userId: "user852",
      revenueSource: "Advertisements",
    },
    {
      id: "6",
      songName: "Stay",
      artist: "The Kid LAROI, Justin Bieber",
      dateStreamed: "2024-09-07",
      streamCount: 920,
      userId: "user369",
      revenueSource: "Subscriptions",
    },
    {
      id: "7",
      songName: "Industry Baby",
      artist: "Lil Nas X, Jack Harlow",
      dateStreamed: "2024-09-06",
      streamCount: 1_050,
      userId: "user159",
      revenueSource: "Subscriptions",
    },
    {
      id: "8",
      songName: "Montero (Call Me By Your Name)",
      artist: "Lil Nas X",
      dateStreamed: "2024-09-08",
      streamCount: 870,
      userId: "user753",
      revenueSource: "Advertisements",
    },
    {
      id: "9",
      songName: "Levitating",
      artist: "Dua Lipa",
      dateStreamed: "2024-09-05",
      streamCount: 980,
      userId: "user951",
      revenueSource: "Subscriptions",
    },
    {
      id: "10",
      songName: "Save Your Tears",
      artist: "The Weeknd",
      dateStreamed: "2024-09-07",
      streamCount: 790,
      userId: "user486",
      revenueSource: "Subscriptions",
    },
    {
      id: "11",
      songName: "Blinding Lights",
      artist: "The Weeknd",
      dateStreamed: "2024-09-06",
      streamCount: 1_100,
      userId: "user258",
      revenueSource: "Advertisements",
    },
    {
      id: "12",
      songName: "Peaches",
      artist: "Justin Bieber, Daniel Caesar, Giveon",
      dateStreamed: "2024-09-08",
      streamCount: 820,
      userId: "user654",
      revenueSource: "Subscriptions",
    },
    {
      id: "13",
      songName: "Drivers License",
      artist: "Olivia Rodrigo",
      dateStreamed: "2024-09-05",
      streamCount: 960,
      userId: "user321",
      revenueSource: "Subscriptions",
    },
    {
      id: "14",
      songName: "Good 4 U",
      artist: "Olivia Rodrigo",
      dateStreamed: "2024-09-07",
      streamCount: 780,
      userId: "user789",
      revenueSource: "Advertisements",
    },
    {
      id: "15",
      songName: "Butter",
      artist: "BTS",
      dateStreamed: "2024-09-06",
      streamCount: 1_020,
      userId: "user147",
      revenueSource: "Subscriptions",
    },
    {
      id: "16",
      songName: "Dynamite",
      artist: "BTS",
      dateStreamed: "2024-09-08",
      streamCount: 910,
      userId: "user587",
      revenueSource: "Subscriptions",
    },
    {
      id: "17",
      songName: "Permission to Dance",
      artist: "BTS",
      dateStreamed: "2024-09-05",
      streamCount: 850,
      userId: "user963",
      revenueSource: "Advertisements",
    },
    {
      id: "18",
      songName: "Watermelon Sugar",
      artist: "Harry Styles",
      dateStreamed: "2024-09-07",
      streamCount: 990,
      userId: "user258",
      revenueSource: "Subscriptions",
    },
    {
      id: "19",
      songName: "Adore You",
      artist: "Harry Styles",
      dateStreamed: "2024-09-06",
      streamCount: 770,
      userId: "user159",
      revenueSource: "Subscriptions",
    },
    {
      id: "20",
      songName: "Falling",
      artist: "Harry Styles",
      dateStreamed: "2024-09-08",
      streamCount: 1_080,
      userId: "user357",
      revenueSource: "Advertisements",
    },
  ],
};
