export const sampleData = {
  totalUsers: 1000000,
  activeUsers: 750000,
  totalStreams: 5000000,
  revenue: 100000,
  topArtist: "Taylor Swift",
  userGrowth: [
    { month: "Jan", totalUsers: 900000, activeUsers: 700000 },
    { month: "Feb", totalUsers: 920000, activeUsers: 710000 },
    { month: "Mar", totalUsers: 945000, activeUsers: 725000 },
    { month: "Apr", totalUsers: 960000, activeUsers: 730000 },
    { month: "May", totalUsers: 975000, activeUsers: 740000 },
    { month: "Jun", totalUsers: 990000, activeUsers: 745000 },
    { month: "Jul", totalUsers: 1000000, activeUsers: 750000 },
    { month: "Aug", totalUsers: 1010000, activeUsers: 755000 },
    { month: "Sep", totalUsers: 1025000, activeUsers: 760000 },
    { month: "Oct", totalUsers: 1035000, activeUsers: 765000 },
    { month: "Nov", totalUsers: 1045000, activeUsers: 770000 },
    { month: "Dec", totalUsers: 1050000, activeUsers: 775000 },
  ],
  revenueDistribution: [
    { source: "Subscriptions", value: 8000000 },
    { source: "Advertisements", value: 1500000 },
    { source: "Merchandise", value: 500000 },
  ],
  topSongs: [
    { name: "Lavender Haze", streams: 1000000, artist: "Taylor Swift" },
    { name: "Karma", streams: 900000, artist: "Taylor Swift" },
    { name: "As It Was", streams: 800000, artist: "Harry Styles" },
    { name: "Bad Habit", streams: 700000, artist: "Steve Lacy" },
    { name: "Heat Waves", streams: 600000, artist: "Glass Animals" },
    { name: "Stay", streams: 550000, artist: "The Kid LAROI, Justin Bieber" },
    {
      name: "Industry Baby",
      streams: 500000,
      artist: "Lil Nas X, Jack Harlow",
    },
    {
      name: "Montero (Call Me By Your Name)",
      streams: 450000,
      artist: "Lil Nas X",
    },
    { name: "Levitating", streams: 400000, artist: "Dua Lipa" },
    { name: "Save Your Tears", streams: 350000, artist: "The Weeknd" },
    { name: "Blinding Lights", streams: 300000, artist: "The Weeknd" },
    {
      name: "Peaches",
      streams: 250000,
      artist: "Justin Bieber, Daniel Caesar, Giveon",
    },
    { name: "Drivers License", streams: 200000, artist: "Olivia Rodrigo" },
    { name: "Good 4 U", streams: 150000, artist: "Olivia Rodrigo" },
    { name: "Butter", streams: 100000, artist: "BTS" },
    { name: "Dynamite", streams: 90000, artist: "BTS" },
    { name: "Permission to Dance", streams: 80000, artist: "BTS" },
    { name: "Watermelon Sugar", streams: 70000, artist: "Harry Styles" },
    { name: "Adore You", streams: 60000, artist: "Harry Styles" },
    { name: "Falling", streams: 50000, artist: "Harry Styles" },
  ],
  recentStreams: [
    {
      id: 1,
      songName: "Lavender Haze",
      artist: "Taylor Swift",
      dateStreamed: "2024-09-08",
      streamCount: 1000,
      userId: "user123",
      revenueSource: "Subscriptions",
    },
    {
      id: 2,
      songName: "Karma",
      artist: "Taylor Swift",
      dateStreamed: "2024-09-07",
      streamCount: 950,
      userId: "user456",
      revenueSource: "Advertisements",
    },
    {
      id: 3,
      songName: "As It Was",
      artist: "Harry Styles",
      dateStreamed: "2024-09-06",
      streamCount: 1200,
      userId: "user789",
      revenueSource: "Subscriptions",
    },
    {
      id: 4,
      songName: "Bad Habit",
      artist: "Steve Lacy",
      dateStreamed: "2024-09-05",
      streamCount: 880,
      userId: "user246",
      revenueSource: "Subscriptions",
    },
    {
      id: 5,
      songName: "Heat Waves",
      artist: "Glass Animals",
      dateStreamed: "2024-09-08",
      streamCount: 760,
      userId: "user852",
      revenueSource: "Advertisements",
    },
    {
      id: 6,
      songName: "Stay",
      artist: "The Kid LAROI, Justin Bieber",
      dateStreamed: "2024-09-07",
      streamCount: 920,
      userId: "user369",
      revenueSource: "Subscriptions",
    },
    {
      id: 7,
      songName: "Industry Baby",
      artist: "Lil Nas X, Jack Harlow",
      dateStreamed: "2024-09-06",
      streamCount: 1050,
      userId: "user159",
      revenueSource: "Subscriptions",
    },
    {
      id: 8,
      songName: "Montero (Call Me By Your Name)",
      artist: "Lil Nas X",
      dateStreamed: "2024-09-08",
      streamCount: 870,
      userId: "user753",
      revenueSource: "Advertisements",
    },
    {
      id: 9,
      songName: "Levitating",
      artist: "Dua Lipa",
      dateStreamed: "2024-09-05",
      streamCount: 980,
      userId: "user951",
      revenueSource: "Subscriptions",
    },
    {
      id: 10,
      songName: "Save Your Tears",
      artist: "The Weeknd",
      dateStreamed: "2024-09-07",
      streamCount: 790,
      userId: "user486",
      revenueSource: "Subscriptions",
    },
    {
      id: 11,
      songName: "Blinding Lights",
      artist: "The Weeknd",
      dateStreamed: "2024-09-06",
      streamCount: 1100,
      userId: "user258",
      revenueSource: "Advertisements",
    },
    {
      id: 12,
      songName: "Peaches",
      artist: "Justin Bieber, Daniel Caesar, Giveon",
      dateStreamed: "2024-09-08",
      streamCount: 820,
      userId: "user654",
      revenueSource: "Subscriptions",
    },
    {
      id: 13,
      songName: "Drivers License",
      artist: "Olivia Rodrigo",
      dateStreamed: "2024-09-05",
      streamCount: 960,
      userId: "user321",
      revenueSource: "Subscriptions",
    },
    {
      id: 14,
      songName: "Good 4 U",
      artist: "Olivia Rodrigo",
      dateStreamed: "2024-09-07",
      streamCount: 780,
      userId: "user789",
      revenueSource: "Advertisements",
    },
    {
      id: 15,
      songName: "Butter",
      artist: "BTS",
      dateStreamed: "2024-09-06",
      streamCount: 1020,
      userId: "user147",
      revenueSource: "Subscriptions",
    },
    {
      id: 16,
      songName: "Dynamite",
      artist: "BTS",
      dateStreamed: "2024-09-08",
      streamCount: 910,
      userId: "user587",
      revenueSource: "Subscriptions",
    },
    {
      id: 17,
      songName: "Permission to Dance",
      artist: "BTS",
      dateStreamed: "2024-09-05",
      streamCount: 850,
      userId: "user963",
      revenueSource: "Advertisements",
    },
    {
      id: 18,
      songName: "Watermelon Sugar",
      artist: "Harry Styles",
      dateStreamed: "2024-09-07",
      streamCount: 990,
      userId: "user258",
      revenueSource: "Subscriptions",
    },
    {
      id: 19,
      songName: "Adore You",
      artist: "Harry Styles",
      dateStreamed: "2024-09-06",
      streamCount: 770,
      userId: "user159",
      revenueSource: "Subscriptions",
    },
    {
      id: 20,
      songName: "Falling",
      artist: "Harry Styles",
      dateStreamed: "2024-09-08",
      streamCount: 1080,
      userId: "user357",
      revenueSource: "Advertisements",
    },
  ],
};
